### ISSUE TITLE
Importing a form with (legacy) Objects API registration results in error

### ISSUE THREAD

**Issue by stevenbal** [open-formulieren/open-forms#4562] opened 2024-07-26 08:21 UTC
### Product versie / Product version

Export from 2.6.12 / Import on cbdf97d17c273e9cba67d3073923a6a928a18370

### Omschrijf het probleem / Describe the bug

When importing a form with (legacy) Objects API registration, the following error occurs:

![image](https://github.com/user-attachments/assets/cc8dfa90-01f9-4217-9dca-482103335c04)

@sergei-maertens mentioned that the changes to add this conversion to the import logic may have been added in one of @Viicos branches, this issue is to ensure we don't lose track of this change

### Stappen om te reproduceren / Steps to reproduce

This can be tested by importing the .zip attached in taiga Gemeente Utrecht Common Ground issue #247

### Verwacht gedrag / Expected behavior

The import should succeed

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment] 2024-09-20 15:48
I can't reproduce this anymore on `stable/2.7.x`, and it appears that c03dfb21929faf8ceb22f4d5b07813e63ecd3f7a fixed this issue (for issue #4516). The timelines for this are close together, but these fixes should have been present given the commit mentioned where the issue occurs 🤔 

I'm going to close this ticket, we can re-open if a customer reports this problem though I don't expect they will.

**Closed by sergei-maertens** 2024-09-20 15:48 UTC
Labels: bug, needs-backport, topic: form import/export
