### ISSUE TITLE
Provide a setting to limit the amount of submission for a form

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4728] opened 2024-10-03 10:20 UTC
### Thema / Theme

Form designer

### Omschrijving / Description

ref:
LV 171
BVWB 41
BEESEL #

As a form designer i want to be able to limit the submissions for a form. 
This will allow me to build forms that have a limit for scenario's like an event with a max capacity of 50 participants. 

The form should once it's reached that limit display a custom message and not show a "start" button.   

### Aanvullende opmerkingen / Additional context

Ideally this limit could also be calculated by a variable in all the submissions - enabling a form where 1 submission contains multiple participants.

**Comment by sergei-maertens** [comment] 2024-10-07 18:34
Duplicate of #4321

**Comment by joeribekker** [comment] 2024-10-21 09:23
Closing in favor of.... ##4321

**Closed by joeribekker** 2024-10-21 09:23 UTC
Labels: enhancement, owner: maykin
