### ISSUE TITLE
Copy/pasted components do not generate a unique variable name - not even in the same step

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2771] opened 2023-02-24 16:31 UTC

**Comment by sergei-maertens** [comment] 2023-02-27 09:26
The key is unique because Formio appends an increment/suffix. However, the label of the field is indeed the same because of the copy action, which is listed under the "Naam" column in the variables.

Editing the component and changing the label _does_ change the name in the variables tab too, and we're unanimous that we'd rather not touch the formio logic to generate a unique label/name on copy paste.

@sergei-maertens check if Laurens knows more

**Comment by LaurensBurger** [comment] 2023-02-27 10:19
Please see this example: 
![image](https://user-images.githubusercontent.com/112621537/221537148-28cac7d7-c017-44f8-acd4-4e8f06148506.png)

for some reason it's not actually creating unique variables in certain conditions

**Comment by LaurensBurger** [comment] 2023-02-27 10:25
Could it be the initial variable is checked and if it exists it will not check if the new variable name is already in use? "naam1" becames "naam2" even if "naam2" already exists?

**Comment by sergei-maertens** [comment] 2023-02-27 13:16
@LaurensBurger 

> for some reason it's not actually creating unique variables in certain conditions

I think we're looking for exactly which conditions these are, since we can't reproduce this at the moment. Do you know which exact commit this was happening in? Do you have steps/a form to reproduce this with?

> Could it be the initial variable is checked and if it exists it will not check if the new variable name is already in use? "naam1" becames "naam2" even if "naam2" already exists?

The duplicate key checks are entirely done in the Formio builder (within the same step) - I can't seem to reproduce this either. We did recently have a bug where the automatic key-update was broken from Formio, but that has since been fixed.

**Comment by LaurensBurger** [comment] 2023-03-01 08:34
This issue was found in 2.1.0.aplha2
Trying to reproduce on our test i cannot reproduce it either.

**Comment by sergei-maertens** [comment] 2023-03-01 09:38
I'm closing this as wontfix then since we can't reproduce - let's keep an eye on it when testing the 2.1.0 release candidate!

**Closed by sergei-maertens** 2023-03-01 09:38 UTC
Labels: bug, formio, triage, prio: low
