### ISSUE TITLE
Incomplete prefill settings causes data to be stored in "random" variables

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2761] opened 2023-02-23 09:06 UTC
### Product versie / Product version

2.0.3

### Omschrijf het probleem / Describe the bug

When a form has prefill fields and one of these fields has the plugin selected, but not the value:
![image](https://user-images.githubusercontent.com/112621537/220861572-a38af1be-66f6-464e-ab98-fe35f229408f.png)

The values that are retrieved with this plugin could end up in random variables that are not present in the form, submission:
![image](https://user-images.githubusercontent.com/112621537/220863165-2bd34d54-9bcf-4e17-93db-49813406a015.png)

Cannot reproduce on latest it won't import form with this config:
> new row for relation "forms_formvariable" violates check constraint "prefill_config_empty_or_complete"

**Comment by joeribekker** [comment] 2023-02-24 09:28
Initial assessment: Sounds like a bug that can be annoying but is caused by improper configuration, so moving to 2.2

**Comment by pi-sigma** [comment] 2023-03-06 15:06
I was unable to reproduce the issue on 2.0.x by creating a form and selecting a prefill plugin without corresponding attribute. I get an `IntegrityError` with the message from above ("new row for relation "forms_formvariable" violates check constraint "prefill_config_empty_or_complete").

Note that the constraint that generates the `IntegrityError` was implemented on 2.0.0 via [PR #1647](https://github.com/open-formulieren/open-forms/commit/ac2dae4778512dd5387723a32798a5d3ebb9f438#diff-5e1b6611e72afcb20d8a93f1270372842a6b642090f67ebb9f5548a9783bd89a), hence it shouldn't be possible to create this setup on 2.0.3

@LaurensBurger Were you able to reproduce the issue yourself? If so, could you post the steps to reproduce the issue?

**Comment by sergei-maertens** [comment] 2023-03-07 09:10
Can't reproduce anymore, feel free to reopen when we can reproduce it.

**Closed by sergei-maertens** 2023-03-07 09:10 UTC
Labels: bug, needs-backport, triage, prio: low
