### ISSUE TITLE
Allow large images in WYSIWYG editor (free text component)

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2604] opened 2023-01-25 09:41 UTC
### Thema / Theme

Form designer

### Omschrijving / Description

internal: odru 11

As a form designer i want to use images (the option is already available) in the free text components. 
When a image is too large the field will show a error: 
![image](https://user-images.githubusercontent.com/112621537/214529403-76c83dcd-5360-48c0-b5cf-9e3c8da5a91c.png)
This is caused by the image being converted to base64 and this exceeds the character limit of the field.

**Comment by SilviaAmAm** [comment] 2023-01-27 14:58
See: https://github.com/open-formulieren/open-forms/issues/2288

**Comment by joeribekker** [comment] 2023-02-24 10:20
Initial assessment: Sounds more like an enhancement since the case is handled properly.

**Comment by joeribekker** [comment] 2023-02-24 10:55
Marking as duplicate of #2288

**Closed** 2023-02-24 10:55 UTC
Labels: enhancement, prio: medium
