### ISSUE TITLE
In importing several forms which share (reuse) form definitions, a separate definition is made for each

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#1906] opened 2022-08-22 14:32 UTC
### Product versie / Product version

1.5.0

### Omschrijf het probleem / Describe the bug

When I export two forms, both sharing the form definition 'Step1' - and consquently import them in a new OpenForms environment - two separate form definitions called 'Step1' are created. 

For example, these definitions called 'Uw gegevens' would be the same (and shared/reused) in the original environment - but appear separately up when ex- and then imported:
![image](https://user-images.githubusercontent.com/111565013/185950060-73aa7a65-050a-449d-8ff5-95058c884f50.png)

### Verwacht gedrag / Expected behavior

For OpenForms to recognise identical (reusable) form steps. 
This could be done by hash, in which case there is no chance of overwriting as the form definitions are guaranteed to be identical. Alternatively by ID; In case of recognising duplicate form steps by ID, the options could be offered to 'Keep both versions separately', 'Merge and keep version A' or 'Merge and keep version B'.

**Comment by sergei-maertens** [comment] 2022-08-22 15:08
I've also noticed this before and it is quite annoying :)

**Comment by sergei-maertens** [comment] 2022-10-18 09:03
There are a couple design decisions to be made here too, since we have both one-time-use form definitions and re-usable form definitions.

* Re-usable form definitions - if the form export contains a re-usable form definition, and it is found in the database (and is marked re-usable), do re-use it IF the definitions are equivalent (hash based now afaik, this should be the way things work now)
* If importing the same form twice, a second form with different slug should be created. Because the FD are not marked as re-usable, a new one should be created
* If importing a form, then delete the form again and import it again, there should not be duplicate form definitions.

I realize the whole import flow can be vastly improved by allowing to pick what to do with duplicates and whether form definitions should be "promoted" to re-usable form definitions :thinking: so we'll have to figure this out in another user story

**Comment by sergei-maertens** [comment] 2022-10-18 09:07
I did just check the test environment mentioned in the original bug report, and none of the form definitions are marked as re-usable, so the behaviour does look as intended at the moment.

**Comment by hlmr-erik** [comment] 2022-10-18 09:12
> 

That's why I formulated it as 'would be' ;) as it was an illustration of a problem I encountered but already resolved by manually re-assigning the form definitions. If it helps I can (try to :p) reproduce it again?
![image](https://user-images.githubusercontent.com/111565013/196388771-6006470b-eb19-4096-bd5f-4d8d40344f52.png)

**Comment by hlmr-erik** [comment] 2022-10-18 11:53
The problem doesn't seem to occur when importing from an 1.1.7 environment and then re-importing in the same one. I'm curious to see how it behaves between environments/versions now. The original bug report occured when exporting from a local 2.* instance and importing in our official testing environment in the cloud (at that time running 1.1.5)

**Comment by sergei-maertens** [comment] 2022-10-18 13:08
Thanks for the extra input - different major versions of environments will likely give different results because the internal formio configuration saved will/may have gained/lost certain attributes depending on which features were added or tweaked. This is something we'll have to keep in mind!

**Comment by CharString** [comment] 2022-10-19 08:44
I haven't been able to reproduce the issue. On 2.* (b4807fcb) I've created and exported 2 forms sharing a  reusable form definition and imported both forms back into the same version and into 1.1.5 (cd242886) as [mentioned](#issuecomment-1282264383). No duplicates were created.

**Comment by sergei-maertens** [comment] 2022-10-19 09:16
@hlmr-erik I'm closing this issue as we don't seem to be able to reproduce this - if you happen to run into it again, feel free to re-open and include exact steps on how to reproduce. You can then also attach the form exports (or send them to us via Taiga) so we can reproduce this ourselves.

**Comment by hlmr-erik** [comment] 2024-04-10 08:41
To reproduce: 
-Export two forms that share a common (reusable) form definition from a 2.6.2 environment
-Import them in another instance running the 2.6.2 version
-Observe in the form definitions overview that two instances of the same reusable definition have been made

**Comment by sergei-maertens** [comment] 2024-04-10 09:48
I think the difference here is that multiple forms are exported and imported in one go, rather than one by one. Seems related to #4133

**Comment by vaszig** [comment] 2024-05-16 09:42
Reopenning this as it is the real problem of #4276.

**Closed** 2024-05-22 08:57 UTC
Labels: bug, owner: maykin
