### ISSUE TITLE
Fix PermissionDenied email inzending

### ISSUE THREAD

**Issue by sjoerdie** [open-formulieren/open-forms#831] opened 2021-10-20 12:37 UTC
Raised by municipality Riddeliemers.nl

Sentry: 291859

![Foutmelding insturen formulier](https://user-images.githubusercontent.com/85243022/138093718-1cedc110-87c3-4b32-a02e-931506d95dc8.JPG)

Also no check mark is shown in the rightmenu next to Bevestiging. 

The email is received.

**Comment by sergei-maertens** [comment] 2022-10-07 16:06
TODO: check if this is still an issue

The 403 is because the submission is removed from the session after completion, this *may* have been caused by a hard refresh.

**Comment by sergei-maertens** [comment] 2022-10-17 08:20
Try some things like hard-refreshing while the confirmation page is still loading etc.

**Comment by joeribekker** [comment] 2023-02-24 13:59
I still see these errors from 1.1.8 up to 2.1.0-beta1 (current latest). It's hard to tell though if these are caused by the same flow as described here. In some cases this IS the correct response.

**Comment by joeribekker** [comment] 2023-02-24 14:01
I'm setting it to medium prio because this really annoying for submitters. It's the only way they can get the PDF so we need to introduce some more leniency on this endpoint or track down the actually cause.

**Comment by joeribekker** [comment] 2023-03-13 10:06
Refinement: @LaurensBurger can you try to make this reproducable for us?

**Comment by LaurensBurger** [comment] 2023-03-15 10:26
I cannot reproduce what's in the screenshot, but found multiple ways of triggering it.

1.1.8: follow link from "pauzeren" after completing the form
1.1.8: Pauze form, after redirect to the start of the form: click on a step or back
![image](https://user-images.githubusercontent.com/112621537/225273422-c9de3cef-2b54-4c11-bf04-af0968997d6f.png)


Looking at the logs it seems this error on 2.x.x versions is almost exclusive to form builders/admin while on 1.1.8 this happens to users. 
I see form builders trying to load submissions that are month's old
I see forms with DigiD authentication that produce the error hours after the last activity was logged

**Comment by sergei-maertens** [comment] 2023-05-22 13:56
I cannot reproduce the above steps anymore now either, but I do suspect this is because of related fixes.

The following mechanism is what I suspect was the cause:

* when you start a form/submission, the ID of that submission is persisted in the `localStorage` of the browser (to help with hard-refreshes and not losing any state)
* the localStorage does not have an expiry date, so you may still have an old ID in there that was not garbage collected
* when you load a form, the frontend checks if there's still an ID for that form, if so, then it will retrieve the existing submission from the API
* if that submission has expired by now in the API, you receive an HTTP 403 and then the generic error handlers kick in

The generic handler should not kick in most of the time, because:

* when we try the retrieval and get an HTTP 403, the ID should get removed from the `localStorage` and a new submission started
* proper cleanup of the ID: open-formulieren/open-forms-sdk#405 - two weeks ago the submission complete + suspend actions now result in cleanup of this ID in the local storage

I can't rule out that this never causes a problem anymore, e.g. someone abandoning their submission and then coming back to the same form after the submission/session was expired might still get the occasional HTTP 403 + error message. When those situations arise, we'll need more specific input to zoom in on the exact sequence of actions to see if we can improve this.

The popup/alert definitely should not happen anymore since we replaced it with React's error boundaries that now display in a fallback UI. We also have detection now of expired sessions and handle those appropriately, so users idling on a step and their session expiring should not be a problem on modern versions.

Finally, looking at Sentry for the backend logs/error reporting of these 403's, I see this applies on the whole version range of 1.1.x -> 2.1.y for now and many of the problems are due to the location API requests for address details, presumably when the session has expired. I reckon this is because those API calls and the exceptions they throw don't trip the formio renderer into the error boundary keeping the form step "active", but that's just an unconfirmed theory.

I'm closing this as wontfix since it can't be reproduced in the current latest versions, but feel free to re-open if it is reproducible.

**Closed by sergei-maertens** 2023-05-22 13:56 UTC
Labels: bug
