### ISSUE TITLE
Verkeerd lettertype bij vrije tekst

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4573] opened 2024-07-31 09:54 UTC
### Product versie / Product version

2.6.13

### Customer reference

Taiga DB #50

### Omschrijf het probleem / Describe the bug

![image](https://github.com/user-attachments/assets/96538094-98bd-4b4f-b665-dfec4786ef70)

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment] 2024-08-19 09:17
Refinement: check if there's perhaps a font-family set because of copy-pasting from somewhere else, and/or otherwise reproduce this.

**Comment by LaurensBurger** [comment] 2024-08-23 10:41
Not an issue - user assumed all text in form should be the same size.

**Comment by sergei-maertens** [comment] 2024-09-20 15:50
This might be addressed/fixed via some CSS changes for #4545 - from 2.8.0 and up.

I'm going to close this because of Lauren's comment above though.

**Closed by sergei-maertens** 2024-09-20 15:50 UTC
Labels: bug

**Comment by sergei-maertens** [comment] 2024-09-23 13:50
Confirming that it *is* working as intended, BUT the changes from #4545 are not applied to Formio WYSIWYG content, which is inconsistent. I'll make an issue for this, since we would like to control the font-size through design tokens.
