### ISSUE TITLE
Set min/max items on more components that allow multiple value

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2956] opened 2023-04-03 07:38 UTC
### Thema / Theme

Form designer

### Omschrijving / Description

Utrecht 50

As a form designer i want to use the same functionality a repeating group and upload field has: i want to set the min/max amount when i select: "multiple values"
I can use this to limit item selection in components like:
Checkboxes
Choicefield
![image](https://user-images.githubusercontent.com/112621537/229442569-9c95e750-d9ba-405f-ba23-f1955f033ac3.png)
![image](https://user-images.githubusercontent.com/112621537/229443787-f9d994ff-4714-4811-bbdd-e172fa47f735.png)

But also components like textfield and Number that do not have items to select from.
![image](https://user-images.githubusercontent.com/112621537/229442506-f0df2228-f90b-46a0-8a27-fea4c51de448.png)

**Comment by joeribekker** [comment] 2024-12-17 17:33
Duplicate of #2812

**Closed** 2024-12-17 17:34 UTC
Labels: triage, enhancement, owner: utrecht
