### ISSUE TITLE
Upload component type is array, but when mapping to objecttype, it's a string. 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4605] opened 2024-08-16 15:33 UTC
### Product versie / Product version

2.6.13

### Customer reference

DH 691

### Omschrijf het probleem / Describe the bug

It seems upload components changes type from string to array by enabling "allow multiple". But it's always shown as a array within Open Forms. 
![image](https://github.com/user-attachments/assets/48a57a30-639a-442f-a689-f21c2f2af164)
When mapping - only strings are shown. 
When trying to map this "single" upload component, arrays are missing from the dropdown. 

(used "oneOF" in schema to work around, and allow both)

**Comment by sergei-maertens** [comment] 2024-08-19 08:35
@LaurensBurger (discussed during refinement) - this is actually working as intended, but Formio's behaviour is a bit unexpected here.

Formio's file upload data type is **always** an array of objects containing the metadata of the file upload, however you can enable/disable multiple file uploads on a per-component case. Even if only a single file is allowed, the underlying Formio data type is an array, it will just have the single element.

Because this is not intuitive when defining the Objecttype schema/contract (i.e. "I expect only one file upload, so I mark the component as multiple-not-allowed"), we apply that configuration from the component and extract the single file, upload it to the documents API and return the single API resource URL, so you get type `string`. If multiple uploads are allowed, we process each file and return an `Array<string>` instead.

Marking this as wontfix - updating the type information in the variables table is also not an option because if you do JsonLogic operations on the component variable, you will be operating on an array, it's only at registration-time that we convert single-upload components to `string` rather than `Array<string>`.

**Closed by sergei-maertens** 2024-08-19 08:35 UTC
Labels: bug, triage
