### ISSUE TITLE
Existing file upload components no longer work.

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2056] opened 2022-09-19 15:58 UTC
### Product versie / Product version

2.0.0-beta0

### Omschrijf het probleem / Describe the bug

Old (1.1.5) file upload components don't work anymore. Files don't get uploaded. When dragging a new one, it works.

![image](https://user-images.githubusercontent.com/96970/191311647-be148bdb-5be8-408c-86e7-c4301f135686.png)

2.0.0-beta0 on the left, 1.1.5 on the right.

**Comment by SilviaAmAm** [comment] 2022-09-20 08:55
I can't reproduce this: 
I made a form with file upload components in OF 1.1.5, then migrated to 2.0.0-beta.0 and the file uploads (both single file and multiple file upload) seem to work.

**Comment by SilviaAmAm** [comment] 2022-09-20 16:36
With the form exported from venray I can reproduce it. I added a new file upload field under the original and I see that:
![Screenshot from 2022-09-20 18-35-48](https://user-images.githubusercontent.com/19154114/191315021-651b4684-a54c-4683-b64d-eb86f45fd31e.png)
They have different initial values :thinking:

**Comment by SilviaAmAm** [comment] 2022-09-21 10:45
I tried changing the empty value that is assigned to the file to an array, but it didn't work.

Digging into Formio shows that [here](https://github.com/formio/formio.js/blob/4.12.7.x/src/components/file/File.js#L674) an error is raised:
```
can't define array index property past the end of an array with non-writable length
```
This error is not displayed because the status for this file was already popped from the statuses [here](https://github.com/formio/formio.js/blob/4.12.7.x/src/components/file/File.js#L668). So the widget doesn't know something went wrong.

I also tried adding a value of `null` instead of `[]` for the empty array but it didn't work. 

What did work was commenting out this part of the check_logic endpoint:

```python
if original_value is not empty:
    if (
        component
        and not is_visible_in_frontend(component, data_container.data)
        and component.get("clearOnHide")
    ):
        data_diff[key] = ""
        continue
```

**Closed** 2022-09-22 07:47 UTC
Labels: bug
