### ISSUE TITLE
"defaultValue": null, breaks logic with empty value in trigger

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2131] opened 2022-10-07 14:35 UTC
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

With (form)logic: 
If "Trigger field" is not equal to the value ""
-> Action

When the user deletes the value from "Trigger field" - which should trigger the action. But instead because the defaultValue is set to "null" i believe the action is not triggered.
![image](https://user-images.githubusercontent.com/112621537/194577968-1aa6fd54-40ca-47d6-9bee-17a4a48099e2.png)

If you change the "Trigger field" JSON to "defaultValue": "", seems to solve the issue:
![image](https://user-images.githubusercontent.com/112621537/194578670-816996cd-2557-49c8-8865-a2bf5db49240.png)

internal ref: SED14

**Comment by SilviaAmAm** [comment] 2022-10-07 14:42
I think this may happen because data of invalid fields is not sent to the backend for the logic checks:
https://github.com/open-formulieren/open-forms-sdk/blob/main/src/components/FormStep.js#L100

**Comment by SilviaAmAm** [comment] 2022-12-07 11:49
Potentially also fixed by https://github.com/open-formulieren/open-forms/pull/2443 ?

**Comment by sergei-maertens** [comment] 2022-12-07 11:57
when it's merged, I'll validate it :)

**Comment by sergei-maertens** [comment] 2022-12-08 15:47
Spent some time trying to reproduce this on latest master - it does not sound related at all to #2443, but other patches may have fixed this (especially the `get_empty_value_for_component` in submission form logic evaluation).

So, we're considering this one fixed unless proven otherwise - feel free to reopen if there is better information on how to reproduce this.

**Closed by sergei-maertens** 2022-12-08 15:47 UTC
Labels: bug
