### ISSUE TITLE
Content type is not set with documents

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2089] opened 2022-09-28 18:30 UTC
### Product versie / Product version

1.1.5

### Omschrijf het probleem / Describe the bug

Content-type is not provided for documents  in the StUF ZDS backend.

Ref. SED 15

**Comment by sergei-maertens** [comment] 2022-09-29 09:26
Duplicate of #1746

**Closed by sergei-maertens** 2022-09-29 09:26 UTC
Labels: bug
