### ISSUE TITLE
"continue_url" from paused submission should point to same location/domain as "form_url"

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4352] opened 2024-06-04 08:55 UTC
### Product versie / Product version

2.6.7

### Customer reference

utrecht: 233

### Omschrijf het probleem / Describe the bug

If a form is embedded, the continue url should be generated the same way form_url is generated, and not point to the domain the forms are hosted on.

**Comment by joeribekker** [comment] 2024-06-10 09:00
Refinement: In `get_...url` something on `Submission` there's some logic used to which URL should be used for co-signing. This logic/function is not used for the `continue-url` in the email template.

**Comment by sergei-maertens** [comment] 2024-06-10 09:58
if I remember correctly, this is deliberate because the backend first needs to validate the token in the URL and populate the session data, and only then redirects you to the public frontend.

Appointment change/cancel links work the same way.

**Comment by joeribekker** [comment] 2024-06-10 10:04
In retrospect I'm not sure if this is a problem (still) but it was something we noticed.

**Comment by sergei-maertens** [comment] 2024-06-18 12:42
Looked at the source issue in Taiga - this was about the public frontend URL being stripped out of the emails since the domain was not added to the allow list in the global configuration.

Works as intended, closing as wontfix.

**Closed by sergei-maertens** 2024-06-18 12:42 UTC
Labels: bug, needs-backport, discuss, owner: utrecht
