### ISSUE TITLE
Option for 'Allow negative values' in currency field doesn't work

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#2724] opened 2023-02-16 14:45 UTC
### Product versie / Product version

2.0.3

### Omschrijf het probleem / Describe the bug

When checking the 'Allow negative values' box, the validation at first accepts the negative value; however when trying to navigate to the next tab it gives back:
![image](https://user-images.githubusercontent.com/111565013/219395758-93ac0642-6d54-4619-9ae6-2ef870efa0bd.png)

Though this seems to have been implemented here: https://github.com/open-formulieren/open-forms/issues/1351 ?

### Stappen om te reproduceren / Steps to reproduce

1. Create a new form
2. Add a 'currency' field
3. Check 'Allow negative values' in the component settings
4. Fill in -12345
5. Try to proceed to the next step

### Screen resolution

None

### Device

None

### OS

Windows

### Browser

Firefox

**Comment by LaurensBurger** [comment] 2023-02-17 08:12
@hlmr-erik cannot reproduce, it also doesn't really look like a OF warning/error but rather from the browser. 
Does the field have any other conditions? perhaps you can provide the json of the component.

**Comment by hlmr-erik** [comment] 2023-02-17 08:26
No other conditions, I created an empty form with just this component in it to test: https://haarlemmermeer.test.open-formulieren.nl/negative-currency-no-bueno-demo/

Short JSON of the component:
`{
  "key": "currency",
  "type": "currency",
  "input": true,
  "label": "Currency",
  "currency": "EUR",
  "validate": {
    "required": true
  },
  "delimiter": true,
  "showInPDF": true,
  "tableView": false,
  "showInEmail": false,
  "registration": {
    "attribute": ""
  },
  "allowNegative": true,
  "showInSummary": true,
  "isSensitiveData": false
}`

Full schema:
`{
  "key": "currency",
  "type": "currency",
  "input": true,
  "label": "Currency",
  "currency": "EUR",
  "validate": {
    "required": true,
    "custom": "",
    "customPrivate": false,
    "strictDateValidation": false,
    "multiple": false,
    "unique": false,
    "min": "",
    "max": "",
    "step": "any",
    "integer": ""
  },
  "delimiter": true,
  "showInPDF": true,
  "tableView": false,
  "showInEmail": false,
  "registration": {
    "attribute": ""
  },
  "allowNegative": true,
  "showInSummary": true,
  "isSensitiveData": false,
  "placeholder": "",
  "prefix": "",
  "customClass": "",
  "suffix": "",
  "multiple": false,
  "defaultValue": null,
  "protected": false,
  "unique": false,
  "persistent": true,
  "hidden": false,
  "clearOnHide": true,
  "refreshOn": "",
  "redrawOn": "",
  "modalEdit": false,
  "dataGridLabel": false,
  "labelPosition": "top",
  "description": "",
  "errorLabel": "",
  "tooltip": "",
  "hideLabel": false,
  "tabindex": "",
  "disabled": false,
  "autofocus": false,
  "dbIndex": false,
  "customDefaultValue": "",
  "calculateValue": "",
  "calculateServer": false,
  "widget": {
    "type": "input"
  },
  "attributes": {},
  "validateOn": "change",
  "conditional": {
    "show": null,
    "when": null,
    "eq": ""
  },
  "overlay": {
    "style": "",
    "left": "",
    "top": "",
    "width": "",
    "height": ""
  },
  "allowCalculateOverride": false,
  "encrypted": false,
  "showCharCount": false,
  "showWordCount": false,
  "properties": {},
  "allowMultipleMasks": false,
  "id": "egheui",
  "keyModified": true
}`

**Comment by hlmr-erik** [comment] 2023-02-17 08:41
Thank you for checking. I supposed the issue should have been resolved and backported, but now I see that was for the FE part only - and there is a SDK part as well

**Comment by sergei-maertens** [comment] 2023-02-20 11:39
Seems like this was an error in the backporting process - it will be included with Open Forms 2.0.4. Thanks for spotting this :)

**Closed** 2023-02-28 10:43 UTC
Labels: bug, needs-backport
