### ISSUE TITLE
Form copying with logic rules that contain: "Inschakelen vanaf stap:" breaks Logic tab in new copy

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3378] opened 2023-08-18 08:23 UTC
### Product versie / Product version

2.2.x - 2.3.0
Haarlemmermeer: 28

### Omschrijf het probleem / Describe the bug

If a form containing logic rules that are enabled from a certain step, the copy of the form will have a broken Logic tab as it seems the "Inschakelen vanaf stap" still pointing to the original form:

```json
 {
        "uuid": "de3cc210-aa72-437c-9e37-8aeec24ebe5b",
        "url": "http://localhost/api/v2/forms/de3cc210-aa72-437c-9e37-8aeec24ebe5b/logic-rules",
        "form": "http://localhost/api/v2/forms/1dacaf4f-bc68-4197-8c7b-84ad7ec913c1",
        "json_logic_trigger": true,
        "description": "",
        "order": 3,
        "trigger_from_step": "http://localhost/api/v2/forms/1dacaf4f-bc68-4197-8c7b-84ad7ec913c1/steps/72d4bdb5-90f0-4d89-9c3b-1bf3373c49d7",
        "actions": [
            {
                "component": "",
                "variable": "lijstvoorkvkvestiginen",
                "form_step": "",
                "form_step_uuid": null,
                "action": {
                    "type": "variable",
                    "value": ...
                }
            }
        ],
        "is_advanced": true
    }
```

json in copied form, notice the: `"trigger_from_step": "http://localhost/api/v2/forms/1dacaf4f-bc68-4197-8c7b-84ad7ec913c1/steps/72d4bdb5-90f0-4d89-9c3b-1bf3373c49d7"` instead of `http://localhost/api/v2/forms/1968d36e-8932-43ff-8a83-8c22a2ad97dd`
```json
    {
        "uuid": "5fa0ea6f-c0d8-43b5-adb0-ad2584208bda",
        "url": "http://localhost/api/v2/forms/5fa0ea6f-c0d8-43b5-adb0-ad2584208bda/logic-rules",
        "form": "http://localhost/api/v2/forms/1968d36e-8932-43ff-8a83-8c22a2ad97dd",
        "json_logic_trigger": true,
        "description": "",
        "order": 3,
        "trigger_from_step": "http://localhost/api/v2/forms/1dacaf4f-bc68-4197-8c7b-84ad7ec913c1/steps/72d4bdb5-90f0-4d89-9c3b-1bf3373c49d7",
        "actions": [
            {
                "component": "",
                "variable": "lijstvoorkvkvestiginen",
                "form_step": "",
                "form_step_uuid": null,
                "action": {
                    "type": "variable",
                    "value": ...
                }
            }
        ],
        "is_advanced": true
    }
```

Importing the form does work.

**Comment by sergei-maertens** [comment] 2023-08-21 08:37
Refinement: this is similar to the logic action to mark a step as not applicable - the solution there was to store the UUID reference rather than the fully qualified API resource URL. A similar approach is needed here.

It's a bug, but not a 2.3.0 release blocker, since it is broken all the way to 2.0.x probably.

**Comment by hlmr-erik** [comment] 2023-08-25 12:56
AFAIK no workaround to 'revive' the logic tab once the form has been copied. As @LaurensBurger mentioned a woraround to get the form duplicated still consists of exporting the original form and then re-importing it - this duplicates the form with a working logic tab.

**Comment by sergei-maertens** [comment] 2023-08-25 13:11
thanks for reporting back! this will be fixed in the upcoming patch releases (in a month at the latest)

**Comment by hlmr-erik** [comment] 2023-08-25 13:25
Regretfully, where everything seemed fine originally, upon editing the export-imported form and trying to save, this showed up:
![afbeelding](https://github.com/open-formulieren/open-forms/assets/111565013/127f9ff5-b874-4cdc-b555-de840b42f24b)

So it seems the workaround isn't one really, as now the copies automagically share their tabs.

**Comment by sergei-maertens** [comment] 2023-08-28 07:36
I believe this may be caused by #3335 - so if we can fix that, then the workaround *should* be viable.

**Closed** 2023-09-18 11:46 UTC
Labels: bug, needs-backport
