### ISSUE TITLE
Bulk Export of submission crash when submission objects with different amount of items in them (repeating groups, uploads)

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3629] opened 2023-11-22 15:33 UTC
### Product versie / Product version

2.2.6

### Omschrijf het probleem / Describe the bug
Bodegr 39
nopolder: 83
venr: 86
RID: 130

sentry: 340715
Bulk export will crash when 2 submissions have a big difference in keys: 

Export generates the headers to merge from submission A:
```python
[
    "Formuliernaam",
    "Inzendingdatum",
    "voornaam",
    "voorvoegsel",
    "achternaam",
    "bsn",
    "straatnaam",
    "huisnummer1",
    "huisletter_persoon",
    "huisnummertoevoegingPersoon",
]

```
But submission B looks like this:
```python	
[
    "Evenementenvergunning aanvragen",
    datetime.datetime(2023, 11, 14, 11, 3, 42, 407842),
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
]
```
Because 
```
    "voornaam",
    "voorvoegsel",
    "achternaam",
    "bsn",
    "straatnaam",
    "huisnummer1",
    "huisletter_persoon",
    "huisnummertoevoegingPersoon",
```
are all empty, these components are all part of a step that was skipped for submission B.

This causes the mass export to fail.

**Comment by Viicos** [comment] 2023-11-24 16:13
After investigation:
- We use `tablib` for our export function, and it expects the rows added to the dataset to be the same length as the headers
- This doesn't seem to be related to a specific number of missing keys, i.e. tablib only makes the following check: `len(row) == len(headers)`
- I might be missing something from sentry, as it shows that the failing row and headers have the same length

**Comment by joeribekker** [comment] 2023-11-27 09:55
Refinement: Lots of discussion to completely refactor export code or to specifically fix certain component serializations. We'll see if we can get an export that goes out of bounds to see where things go wrong.

**Comment by LaurensBurger** [comment] 2024-01-08 08:43
@joeribekker i have 2 submissions as json that cause the "InvalidDimensions" on bulk export

**Comment by LaurensBurger** [comment] 2024-01-23 10:01
update: it seems to also happen when a repeating group is present and submissions have different amount of items in this repeating group.

**Comment by alextreme** [comment] 2024-01-29 11:20
This is also a problem with upload fields (NOP 83). 

Could we go for a workaround in this situation? This seems to be to be a defect, as Laurens explained this occurs when having optional fields (and that submissions which have these fields empty aren't exportable)

**Comment by alextreme** [comment] 2024-05-21 10:29
@joeribekker Discussed with Laurens, could we get an update on this issue? multiple clients have this issue

**Comment by joeribekker** [comment] 2024-05-21 11:56
So, looking at the latest reports. We probably need to serialize the repeating groups differently (ie. so they don't cause different export columns). I think it should be exported in 1 column in a JSON-like format: `[{"group1field1": "val", "group1field2": "val"}, {"group2field1": "val", "group2field2": "val"}]`

**Comment by sergei-maertens** [comment] 2024-05-22 08:39
I find this very arbitrary and opened issues about this before: #2375 and #2376

I see a number of challenges with this:

* the double quotes of JSON data may interfere with the quotes for a column, so those will need escaping
* how will that interact with other export formats (XML)?

CSV/tabular based exports just seem inherently flawed because you need to serialize complex datastructures which require a different data format for parsing. I would really, really like to get some context from the customers on how they are processing this data after having exported it...

About the upload fields - I don't see how that is usable at all, since the export doesn't even include the uploads themselves, there are only (formio data) references with some URLs, and the temporary file uploads themselves should already deleted by the time the export is created.

IMO this ticket needs a lot more upfront design instead of just doing something to make the errors go away.

**Comment by joeribekker** [comment] 2024-08-26 09:17
Refinement: First task should be how to deal with this and get an estimate.

Questions:
1. How does export work now?
2. Can we serialize values based on the export format (thus: separate how it renders for CSV, XML, etc.)

Statements:
1. If you choose a limited format, you should accept an export that has limited value (for complex submission values). So, typically, Excel is a best effort but we try to put in as much data as we can.
2. Export should not crash (this is much more preferred than missing or odd data in cells)

**Comment by sergei-maertens** [comment] 2024-10-02 09:13
Needs to be fixed by December at the latest

**Comment by sergei-maertens** [comment] 2024-10-11 20:18
How does it currently work:

* A queryset of submissions is exported, using a `tablib.Dataset`
* The first submission is used to produce the header columns, but other than that there is no special treatment
* We use the submission rendering (`Renderer`) as a tree visitor in "export" mode, which recursively yields its children. So, this roughly does:
    * Start at the submission
    * Visit all the submission steps, and for each step:
        * Visit the formio configuration. for each component in the configuration:
            * yield the component if it's a "leaf node"
            * recurse into the component if it's a layout node (columns, fieldsets but also editgrid, sort of)
* The (depth first) visiting above is done for each submission, and for each "data node" (either a formio leaf component or a user defined variable), we grab the value of the node and add it to the row data. Note that this value can be of any type - a textfield will produce a string or list of strings, but for files we get complex dictionaries. For non-primitives, tablib uses the python string representation in the final CSV/Excel export

Why did this break:

* a bug that would ignore hidden/skipped/non-applicable submission steps, leading to a different number of submission step nodes to visit, and thus, a different number of columns depending on the data in that particular submission
* in other render modes, we need to recurse into the edit grid to properly display the information, but during export, we actually need to treat it as a single value (a leaf node). Repeating groups are *really weird* and hard.
* I couldn't really see/reproduce a reason why files would fail, they appear to just be properly treated as leaf nodes. The weird thing here is that the entire data structure from formio is dumped (and in particular, the string representation), but that's how it's always been. We don't even include the attached files in the export itself so this information really has always been useless anyway.

**Closed** 2024-10-14 10:03 UTC
Labels: bug, owner: den-haag, needs-backport, topic: submissions export, owner: maykin
