### ISSUE TITLE
Users can submit forms with empty required fields

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3498] opened 2023-09-20 09:54 UTC
### Product versie / Product version

2.3.0

### Omschrijf het probleem / Describe the bug

There have been multiple reports about submission that are missing required fields.
After looking through all these reports there seemed to be no obvious reason/connection how this could happen.

I was able to reproduce it by intercepting each request, removing the data from the required fields, and continuing the form. 
Using burpsuite/zaproxy tools this is possible but for a "normal" user this does not seem likely. 
It seems some form privacy/anti virus browser add-on might be doing the same thing i did and stripping "sensitive" data from the post requests. 

This would be potentially be solved if OF could check if required fields are empty (not None, as those are the ones that are hidden?) before completing the submission.
 

### Stappen om te reproduceren / Steps to reproduce

Intercept POST requests after clicking "Next Step"
Remove data from fields in request body (x3)
complete form

**Comment by sergei-maertens** [comment] 2023-09-20 10:03
Duplicate of #72, #129

**Comment by joeribekker** [comment] 2023-09-25 08:35
Refinement: Can be solved with related tickets in above comment. Requires stakeholder.

**Closed** 2024-03-14 15:57 UTC
Labels: bug
