### ISSUE TITLE
minSelectedCount in Select Box error defaults to English

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4602] opened 2024-08-16 09:02 UTC
### Product versie / Product version

2.6.13 + latest

### Customer reference

Hogeland 27

### Omschrijf het probleem / Describe the bug

![image](https://github.com/user-attachments/assets/face695c-bbce-4031-8e64-1f0bfa260c5f)
![image](https://github.com/user-attachments/assets/e8fda64c-fea8-43d3-9537-a858fdce3360)

**Comment by stevenbal** [comment] 2024-09-16 12:03
I cannot reproduce this locally on latest, it seems that this was fixed in a11a1380e16b637c584aa3118303707c1f3499a6.

![image](https://github.com/user-attachments/assets/e6ff8744-e35d-4987-a49e-24523092cac1)

I'll backport this to `stable/2.6.x` and `stable/2.5.x` (it's already part of `stable/2.7.x`)

**Closed** 2024-09-17 09:04 UTC
Labels: bug, needs-backport, topic: vertalingen
