### ISSUE TITLE
Session timeout popup doesn't show when logged in with OIDC

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3760] opened 2024-01-10 16:47 UTC
Can it be that the OIDC timout is shorter than the timeout in the Django session and that this is not accounted for?

**Tasks**

* [ ] Check if the problem is that the popup is not showing for some reason but session is respected, or that the session is not respected.
* [ ] Check the timeout for Django and Keycloak

**Comment by SilviaAmAm** [comment] 2024-01-19 16:29
Could not reproduce. Discussed with Joeri, closing for now.

**Closed by SilviaAmAm** 2024-01-19 16:29 UTC
Labels: bug, topic: autorisatie en gebruikersbeheer
