### ISSUE TITLE
File upload "breaks" after error

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2452] opened 2022-12-08 10:23 UTC
### Product versie / Product version

2.0.1

### Omschrijf het probleem / Describe the bug

internal: hadm 41

When the user wants to upload a file that is not allowed or too big the user will se a error:
![image](https://user-images.githubusercontent.com/112621537/206422060-8f8c13dc-3de5-4fed-b2fc-f70daca94683.png)
The user then proceeds to click the X and remove the invalid file, causing the upload field to disappear entirely:
![image](https://user-images.githubusercontent.com/112621537/206422249-283e16f7-aa71-4882-8fbf-c295e5b82452.png)

### Verwacht gedrag / Expected behavior

The user should be shown:
![image](https://user-images.githubusercontent.com/112621537/206422411-71155c49-4087-4673-9c46-f9accd90af83.png)
after removing the invalid files

**Comment by sergei-maertens** [comment] 2022-12-08 11:54
Duplicate of #2335, fix is to be included in 2.1.0

**Closed** 2022-12-09 13:47 UTC
Labels: bug, duplicate
